# https://github.com/rails/solid_cable

default: &default
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  message_retention: 1.day
  polling_interval: 0.1.seconds

development:
  <<: *default

test:
  adapter: test

production: &production
  <<: *default

staging:
  <<: *production
