# https://github.com/rails/solid_cache

default: &default
  database: cache
  store_options: &default_store_options
    max_age: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production: &production
  <<: *default
  store_options:
    <<: *default_store_options
    max_age: <%= 60.days.to_i %>

staging:
  <<: *production
