default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url:      <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  # primary: &primary_development
  #   <<: *default
  # cache:
  #   <<: *primary_development
  # queue:
  #   <<: *primary_development
  # cable:
  #   <<: *primary_development

test:
  <<: *default

production:
  <<: *default
