# Prevent segmentation fault on Apple Silicon devices
# https://github.com/ged/ruby-pg/issues/538#issuecomment-1610120680
disable_gssencmode: &disable_gssencmode
  <% if RUBY_PLATFORM =~ /darwin/ %>gssencmode: disable<% end %>

default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  url:      <%= ENV['DATABASE_URL'] %>

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate

queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate

cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: [*default, *disable_gssencmode]
  cache:
    <<: [*cache, *disable_gssencmode]
    url: <%= ENV['DATABASE_URL']&.+('_cache') %>
  queue:
    <<: [*queue, *disable_gssencmode]
    url: <%= ENV['DATABASE_URL']&.+('_queue') %>
  cable:
    <<: [*cable, *disable_gssencmode]
    url: <%= ENV['DATABASE_URL']&.+('_cable') %>

test:
  <<: [*default, *disable_gssencmode]

production: &production_db
  primary:
    <<: *default
  cache:
    <<: *cache
    url: <%= ENV['DATABASE_URL_QUEUE'] %>
  queue:
    <<: *queue
    url: <%= ENV['DATABASE_URL_QUEUE'] %>
  cable:
    <<: *cable
    url: <%= ENV['DATABASE_URL_CABLE'] %>

staging:
  <<: *production_db
