default: &default_db
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url:      <%= ENV['DATABASE_URL'] %>

cache: &cache_db
  <<: *default_db
  migrations_paths: db/cache_migrate

queue: &queue_db
  <<: *default_db
  migrations_paths: db/queue_migrate

cable: &cable_db
  <<: *default_db
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *default_db
  cache:
    <<: *cache_db
    url: <%= ENV['DATABASE_URL']&.+('_cache') %>
  queue:
    <<: *queue_db
    url: <%= ENV['DATABASE_URL']&.+('_queue') %>
  cable:
    <<: *cable_db
    url: <%= ENV['DATABASE_URL']&.+('_cable') %>

test:
  <<: *default_db

production: &production_db
  primary:
    <<: *default_db
  cache:
    <<: *cache_db
    url: <%= ENV.fetch('DATABASE_URL_QUEUE', ENV['DATABASE_URL']) %>
  queue:
    <<: *queue_db
    url: <%= ENV.fetch('DATABASE_URL_QUEUE', ENV['DATABASE_URL']) %>
  cable:
    <<: *cable_db
    url: <%= ENV.fetch('DATABASE_URL_CABLE', ENV['DATABASE_URL']) %>

staging:
  <<: *production_db
